name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: |
           mkdir ~/.npm-global
           npm config set prefix '~/.npm-global'
           npm install -g bats
           bats -v